name: Bedwars
author: thatVainamo, Sniper_GER
version: 1.0
main: de.festival.Bedwars.Main
commands:
  wp.reset:
    usage: /wp.reset
    description: Resets the world to its default state.
  wp.enable:
    usage: /wp.enable
    description: Enables world protection.
  wp.disable:
    usage: /wp.disable
    description: Disables world protection until next restart.
  bedwars.t2:
    usage: /bedwars.t2
    description:
  createspawner:
    usage: /createspawner [spawnrate] [special]
    description: Creates a spawner, spawning the item the player has in it's hand. Allows controlling an effect upon spawning.
  removespawner:
    usage: /removespawner [spawner]
    description: Removes a spawner.
  disablespawner:
    usage: /disablespawner
    description: Disables all spawners.
  enablespawner:
    usage: /enablespawner
    description: Enables all spawners.
  exportspawner:
    usage: /exportspawner
    description: Exports all spawners to JSON format.